version: '3'

services:
#アプリ
  app:
    container_name: web_dev_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db

# DB
  db:
    container_name: web_dev_db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_dev_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyos